name: CI

on: 
  push:
  pull_request:
    branches: 
      - master

jobs:
  Run:
    name: Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          DOCKER_BUILDKIT=1 docker build -o output .
          
      
      - uses: actions/upload-artifact@v3
        with:
          name: hacks
          path: | 
            output
